import Head from 'next/head';
import { Navigation } from '@/components/Navigation';
import Link from 'next/link';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='main'>
        <Link href='/contacts'>
          <button>Contact</button>
        </Link>
        <Link href='/news'>
          <button>News</button>
        </Link>
      </main>
    </>
  );
}
